global using Catalog.Application.Abstractions;
global using Catalog.Domain;
global using EventPlatform.Messaging;
global using EventPlatform.Persistence;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
