apiVersion: v1
kind: Service
metadata:
  name: venue
  labels:
    app.kubernetes.io/name: venue
    app.kubernetes.io/part-of: eventplatform
spec:
  selector:
    app.kubernetes.io/name: venue
  ports:
    - name: http
      port: 80
      targetPort: 8080
