global using EventPlatform.Contracts;
global using EventPlatform.Contracts.Payments;
global using NetArchTest.Rules;
global using NSubstitute;
global using Payments.Application.Abstractions;
global using Payments.Application.Charging;
global using Payments.Domain;
global using Shouldly;
global using Xunit;
