global using EventPlatform.Contracts.Ordering;
global using EventPlatform.Hosting;
global using Microsoft.EntityFrameworkCore;
global using Ticketing.Api.Endpoints;
global using Ticketing.Application;
global using Ticketing.Application.Abstractions;
global using Ticketing.Application.Issuing;
global using Ticketing.Domain;
global using Ticketing.Infrastructure;
