apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/part-of: eventplatform
spec:
  selector:
    app.kubernetes.io/name: catalog
  ports:
    - name: http
      port: 80
      targetPort: 8080
