apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/part-of: eventplatform
spec:
  selector:
    app.kubernetes.io/name: inventory
  ports:
    - name: http
      port: 80
      targetPort: 8080
