apiVersion: v1
kind: Service
metadata:
  name: ordering
  labels:
    app.kubernetes.io/name: ordering
    app.kubernetes.io/part-of: eventplatform
spec:
  selector:
    app.kubernetes.io/name: ordering
  ports:
    - name: http
      port: 80
      targetPort: 8080
