apiVersion: v1
kind: Service
metadata:
  name: ticketing
  labels:
    app.kubernetes.io/name: ticketing
    app.kubernetes.io/part-of: eventplatform
spec:
  selector:
    app.kubernetes.io/name: ticketing
  ports:
    - name: http
      port: 80
      targetPort: 8080
